apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-frontend
  namespace: labs-ci-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/manifests/pricelist-frontend
    repoURL: https://github.com/Purple-Sky-Pirates/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
