apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pricelist
    tier: frontend
  name: thing
  namespace: pricelist
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: pricelist
    tier: frontend
status:
  loadBalancer: {}
