apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: dpcc-coe-demos
spec:
  destination:
    namespace: serverless-test2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/argo-app
    repoURL: https://github.com/Purple-Sky-Pirates/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
